name = "SyntheticLogs"
uuid = "2792cbe7-efcc-4070-ba5f-5b7a97a8032b"
authors = ["Fedor Zolotarev"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
Aqua = "^0.8"
JET = "^0.0.1"
DocStringExtensions = "^0.9"
Test = "^1.6.7"
julia = "^1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
